export const project = {
  title: "OPSD-V",
  subtitle: "On-Policy Self-Distillation for Post-Training Few-Step Autoregressive Video Generators",
  venue: "Project Page",
  paperUrl: "assets/opsdv.pdf",
  codeUrl: "https://github.com/MeiGen-AI/OPSD-V",
  projectUrl: "https://meigen-ai.github.io/OPSD-V/",
  authors: [
    { name: "Hongyu Liu", affiliations: [1, 2], url: "https://kumapowerliu.github.io/" },
    { name: "Chun Wang", affiliations: [1, 2], url: "https://chunwang.site/" },
    { name: "Feng Gao", affiliations: [1], notes: ["*"], url: "https://scholar.google.com/citations?user=lFkCeoYAAAAJ&hl=en" },
    { name: "Xuanhua He", affiliations: [1, 2], url: "https://xuanhuahe.github.io/" },
    { name: "Yue Ma", affiliations: [2], url: "https://mayuelala.github.io/" },
    { name: "Ziyu Wan", affiliations: [3], url: "http://raywzy.com/" },
    { name: "Yong Zhang", affiliations: [1], notes: ["†"], url: "https://auto202603.github.io/" },
    { name: "Xiaoming Wei", affiliations: [1], url: "https://scholar.google.com/citations?user=JXV5yrZxj5MC&hl=zh-CN" },
    { name: "Qifeng Chen", affiliations: [2], notes: ["*"], url: "https://cqf.io/" },
  ],
  affiliations: [
    { id: 1, name: "Meituan" },
    { id: 2, name: "HKUST" },
    { id: 3, name: "City University of Hong Kong" },
  ],
  authorNotes: [
    { symbol: "*", text: "Corresponding authors" },
    { symbol: "†", text: "Project lead" },
  ],
};

export const cases = [
  {
    slug: "ll-mei-great-wall",
    id: "000013",
    title: "Aerial Great Wall",
    backbone: "LongLive",
    benchmark: "MeiBench",
    category: "quality",
    featured: true,
    prompt: "The Great Wall of China is shown from an aerial perspective, with multiple sections of the wall visible. The wall is constructed from large, light-colored bricks, and it features watchtowers with traditional Chinese architecture, characterized by upturned eaves and intricate designs. The watchtowers are spaced at regular intervals along the length of the wall. The surrounding landscape is arid and desert-like, with sparse vegetation and a clear blue sky. The video captures the grandeur and historical significance of the Great Wall, showcasing its impressive scale and the contrast between the ancient structure and the modern cityscape in the background.",
  },
  {
    slug: "ll-mei-coastal-run",
    id: "000055",
    title: "Running by the Coast",
    backbone: "LongLive",
    benchmark: "MeiBench",
    category: "dynamics",
    featured: true,
    prompt: "A person walks along a rocky coastline during sunset, wearing a plaid shirt over a white top, blue jeans, and dark-colored shoes. The ocean waves crash against the rocks, and the sky is a gradient of warm colors, transitioning from orange near the horizon to a deeper blue higher up. The person starts by walking along the rocky terrain, then begins to run towards the ocean. As they run, they spread their arms wide, and the camera follows their movement. The person continues to run and jump, with their arms outstretched, and the ocean waves crashing against the rocks in the background.",
  },
  {
    slug: "ll-mei-antelope",
    id: "000040",
    title: "Antelope in Arid Terrain",
    backbone: "LongLive",
    benchmark: "MeiBench",
    category: "both",
    featured: true,
    prompt: "A solitary antelope, likely a gazelle or similar species, is seen walking across a barren, rocky terrain. The landscape consists of brownish, dry soil with sparse vegetation, including small bushes and shrubs. The antelope, with its light brown coat and distinct markings, moves slowly and deliberately, occasionally pausing to look around. The background consists of a mountainous or hilly terrain with a gradient of brown shades, indicating a dry or arid environment. The antelope is seen walking from left to right across the frame, with its movements steady and unhurried.",
  },
  {
    slug: "ll-movie-gold-rush",
    id: "000009",
    title: "California Gold Rush",
    backbone: "LongLive",
    benchmark: "MovieGenBench",
    category: "quality",
    featured: true,
    prompt: "A historical footage style photograph depicting a bustling gold rush town in California. The scene captures miners panning for gold in a stream, their faces weathered and determined. Behind them, makeshift wooden shacks and tents line the streets, with smoke rising from chimneys. A man in a dusty hat and tattered clothes stands near a sluice box, his hand on his hip, looking out towards the camera with a mix of hope and hardship. The background features rolling hills and dense forests, with a few oxen-drawn wagons in the distance. The photo has a sepia tone and a grainy texture, capturing the essence of the era. A medium shot with a slightly tilted angle.",
  },
  {
    slug: "ll-movie-rabbit-reader",
    id: "000068",
    title: "Rabbit Reading the News",
    backbone: "LongLive",
    benchmark: "MovieGenBench",
    category: "dynamics",
    featured: true,
    prompt: "A charming illustration in a watercolor style of a young white rabbit wearing glasses and reading a newspaper. The rabbit has soft fur, large round ears, and gentle, curious eyes. It sits upright on a cozy armchair, one paw holding the newspaper and the other resting on its knee. The background features a warm living room with a fireplace, a few books on a side table, and a blurred view of a window with falling leaves. The rabbit's expression is one of focused interest, with a slight smile playing on its lips. A close-up shot from a slightly elevated angle, capturing the rabbit's detailed features and the newspaper's headlines.",
  },
  {
    slug: "ll-movie-orangutan-family",
    id: "000023",
    title: "Orangutan Family",
    backbone: "LongLive",
    benchmark: "MovieGenBench",
    category: "both",
    featured: true,
    prompt: "A nature photography style photo capturing a family of orangutans along the Kinabatangan River in Borneo. The mother orangutan, with long reddish-brown fur and expressive brown eyes, is holding her baby tightly. The baby orangutan, with smaller size and lighter fur, is clinging to its mother's chest, both gazing curiously at the camera. The father orangutan, larger and more muscular, is standing nearby, looking contemplative. The riverbank is lush with green foliage, and the water reflects the surrounding tropical rainforest. A medium shot from a slightly elevated angle, capturing the interaction between the family.",
  },
  {
    slug: "sf-mei-tree-lined-park",
    id: "000010",
    title: "Tree-Lined Park",
    backbone: "Self-Forcing",
    benchmark: "MeiBench",
    category: "quality",
    featured: true,
    prompt: "A lush, green landscape with numerous tall trees standing in a straight line, casting shadows on the ground. The trees have thick trunks and dense foliage, and the grass is vibrant and well-maintained. The sunlight filters through the leaves, creating a dappled effect on the ground. The sky is clear and blue, indicating a sunny day. The camera moves slowly, capturing the serene and tranquil atmosphere of the area.",
  },
  {
    slug: "sf-mei-home-workout",
    id: "000069",
    title: "Home Workout",
    backbone: "Self-Forcing",
    benchmark: "MeiBench",
    category: "dynamics",
    featured: true,
    prompt: "A person performs a series of exercises on a black exercise mat in a room with a white wall and several potted plants. They are wearing a white sports bra and patterned shorts. The sequence starts with the person sitting on the mat, then lying down, and finally lifting their legs and arms. The background includes a white wall, a shelf with plants, and a lit candle. The person is performing a series of leg lifts and crunches, with a countdown timer starting from 30 seconds and decreasing by one second in each subsequent image.",
  },
  {
    slug: "sf-mei-sunset-coast",
    id: "000055",
    title: "Sunset Coast",
    backbone: "Self-Forcing",
    benchmark: "MeiBench",
    category: "both",
    featured: true,
    prompt: "A person walks along a rocky coastline during sunset, wearing a plaid shirt over a white top, blue jeans, and dark-colored shoes. The ocean waves crash against the rocks, and the sky is a gradient of warm colors. The person starts by walking along the rocky terrain, then begins to run towards the ocean. As they run, they spread their arms wide, and the camera follows their movement. The person continues to run and jump, with their arms outstretched.",
  },
  {
    slug: "sf-movie-underwater-tunnel",
    id: "000076",
    title: "Underwater Tunnel",
    backbone: "Self-Forcing",
    benchmark: "MovieGenBench",
    category: "quality",
    featured: true,
    prompt: "A first-person view shot zooming through a narrow tunnel, transitioning into a vibrant underwater world. The tunnel walls are illuminated by colorful lights, creating a mesmerizing effect. Inside the tunnel, bubbles rise gently, and seaweed sways gracefully. The underwater space is filled with a variety of colorful fish swimming around, including neon blue tangs and vibrant orange clownfish. Coral reefs in shades of pink, purple, and green add depth and texture to the scene. The water is clear, allowing visibility of the diverse marine life. The camera angle is slightly tilted, capturing the excitement and adventure of the journey.",
  },
  {
    slug: "sf-movie-candle-monster",
    id: "000004",
    title: "Monster and Candle",
    backbone: "Self-Forcing",
    benchmark: "MovieGenBench",
    category: "dynamics",
    featured: true,
    prompt: "A close-up 3D animated scene of a short, fluffy monster kneeling beside a melting red candle. The monster has large, wide eyes and an open mouth, gazing at the flame with a look of wonder and curiosity. Its soft, fluffy fur contrasts with the warm, dramatic lighting that highlights every detail of its gentle, innocent expression. The pose conveys a sense of playfulness and exploration, as if the creature is discovering the world for the first time. The background features a cozy, warmly lit room with subtle hints of a fireplace and soft furnishings.",
  },
  {
    slug: "sf-movie-surfing-otter",
    id: "000040",
    title: "Surfing Otter",
    backbone: "Self-Forcing",
    benchmark: "MovieGenBench",
    category: "both",
    featured: true,
    prompt: "A charming 3D digital render art style image showcasing an adorable and happy otter confidently standing on a surfboard, wearing a bright yellow lifejacket. The otter is depicted with a joyful expression, its fur soft and detailed, and it appears to glide gracefully through turquoise tropical waters. The background features lush tropical islands with vibrant green foliage and palm trees, creating a serene and picturesque setting. The water is crystal clear, with gentle waves and sunlight filtering through. A medium shot captures the otter mid-glide, with a slight camera tilt emphasizing its playful and adventurous spirit.",
  },
].map((item) => ({
  ...item,
  baseVideo: `assets/videos/${item.slug}-base.mp4`,
  oursVideo: `assets/videos/${item.slug}-opsdv.mp4`,
}));

export const categoryMeta = {
  quality: {
    label: "Long-horizon Quality",
    short: "Quality",
    description: "Reduced visual drift and error accumulation over the one-minute rollout.",
  },
  dynamics: {
    label: "Motion Dynamics",
    short: "Dynamics",
    description: "Stronger and more sustained motion without changing the four-step sampler.",
  },
  both: {
    label: "Quality + Dynamics",
    short: "Quality + Dynamics",
    description: "Improved motion together with a cleaner, more stable long-horizon trajectory.",
  },
};

export const metrics = [
  { method: "LongLive", params: "1.3B", nfe: "4", quality: "0.8138", dynamics: "0.5012", semantic: "0.4911", best: ["semantic"] },
  { method: "LongLive + OPSD-V", params: "1.3B", nfe: "4", quality: "0.8242", dynamics: "0.5890", semantic: "0.4904", best: ["quality", "dynamics"], ours: true },
  { method: "Self-Forcing", params: "1.3B", nfe: "4", quality: "0.8259", dynamics: "0.6218", semantic: "0.4897", best: ["semantic"] },
  { method: "Self-Forcing + OPSD-V", params: "1.3B", nfe: "4", quality: "0.8389", dynamics: "0.6570", semantic: "0.4864", best: ["quality", "dynamics"], ours: true },
];

export const bibtex = `@article{liu2026opsdv,
  title   = {OPSD-V: On-Policy Self-Distillation for Post-Training
             Few-Step Autoregressive Video Generators},
  author  = {Liu, Hongyu and Wang, Chun and Gao, Feng and He, Xuanhua
             and Ma, Yue and Wan, Ziyu and Zhang, Yong and Wei, Xiaoming
             and Chen, Qifeng},
  year    = {2026}
}`;
